//go:build ignore

package main

import (
	"encoding/base64"
	"fmt"
	"log"
	"os"
	"strings"
)

const (
	sourcePath = "web/src/js/jaylive.source.js"
	outputPath = "web/static/js/jaylive.js"
	chunkSize  = 96
	xorKey     = byte(91)
)

func main() {
	source, err := os.ReadFile(sourcePath)
	if err != nil {
		log.Fatal(err)
	}

	encoded := xorCopy(source, xorKey)
	payload := base64.StdEncoding.EncodeToString(encoded)
	chunks := split(payload, chunkSize)

	var out strings.Builder
	out.WriteString("// Generated by tools/obfuscate_jaylive.go. Edit web/src/js/jaylive.source.js instead.\n")
	out.WriteString("(()=>{")
	out.WriteString("const _0x4a9d=")
	out.WriteString("[")
	for i, chunk := range chunks {
		if i > 0 {
			out.WriteString(",")
		}
		out.WriteString(fmt.Sprintf("%q", chunk))
	}
	out.WriteString("].join('');")
	out.WriteString("const _0x2f31=91;")
	out.WriteString("const _0xb7c2=atob(_0x4a9d);")
	out.WriteString("let _0x91e0='';")
	out.WriteString("for(let _0x6d42=0;_0x6d42<_0xb7c2.length;_0x6d42++){")
	out.WriteString("_0x91e0+=String.fromCharCode(_0xb7c2.charCodeAt(_0x6d42)^_0x2f31);")
	out.WriteString("}")
	out.WriteString("(0,Function)(_0x91e0)();")
	out.WriteString("})();\n")

	if err := os.WriteFile(outputPath, []byte(out.String()), 0644); err != nil {
		log.Fatal(err)
	}
}

func xorCopy(input []byte, key byte) []byte {
	output := make([]byte, len(input))
	for i, value := range input {
		output[i] = value ^ key
	}
	return output
}

func split(value string, size int) []string {
	if size <= 0 {
		return []string{value}
	}

	chunks := make([]string, 0, len(value)/size+1)
	for len(value) > size {
		chunks = append(chunks, value[:size])
		value = value[size:]
	}
	if value != "" {
		chunks = append(chunks, value)
	}
	return chunks
}
